// Take the string/wire format as generated by the python library
// as an arg, see if that can be converted to JSON, and instantiated
// into a pond.TimeSeries object. Then round trip the wire format
// back to the calling code to see if that can be instantiated
// and checked against the origianl data structure.

var pond = require('pondjs')
var myArgs = process.argv.slice(2);

var wire;
var series;

switch(myArgs[0]) {
    // This case is so setUp() can reach out and test if the
    // script can be called.
    case 'ping':
        console.log('pong');
        // Explicitly exit on this ping test so subsequent output
        // does not confuse the test in the python unittest setUp()
        // method.
        process.exit(0)
        break;
    // these cases are probably overkill but we might need
    // them sometime so here we go.
    case 'event':
        wire = JSON.parse(myArgs[1]);
        series = new pond.TimeSeries(wire);
        break;
    case 'indexed_event':
        wire = JSON.parse(myArgs[1]);
        series = new pond.TimeSeries(wire);
        break;
    case 'time_range_event':
        wire = JSON.parse(myArgs[1]);
        series = new pond.TimeSeries(wire);
        break;
    default:
        console.log('did not get valid args');
        process.exit(-1)
}

console.log(series.toString());

process.exit(0);
